### ISSUE TITLE
hw2 q4

### ISSUE THREAD

**Issue by luxuriance19** [LFhase/Learning_CS224w#1]
my code of graphsage with dataset enzymes shows a worse result of the performance,  and implementation of mine at GAT get a "DefaultCPUAllocator" error. 
I check the GAT implementation with yours, and it is almost the same. The code of yours run correctly on my computer. Can you share your opinion of this? Thanks.

The implementation of the GraphSAGE is:

```
init:
        # self.lin = None # TODO
        # self.agg_lin = None # TODO
        self.lin = nn.Linear(in_channels+out_channels, out_channels)
        self.agg_lin = nn.Linear(in_channels, out_channels)
forward:
        edge_index, _ = pyg_utils.add_self_loops(edge_index, num_nodes=x.size(0))
        neig_x = self.agg_lin(x)
        # print(neig_x.shape)
        # print(x.shape)
        x = torch.cat([x, neig_x], dim=1)
        out = F.relu(self.lin(x))
update:
        if self.normalize_emb:
             aggr_out = F.normalize(aggr_out, 2, dim=-1) #None # TODO
```
The difference of yours at the GAT is :
```
message
        # alpha = None # TODO
        x_i_view = x_i.view(-1, self.heads, self.out_channels)
        x_j_view = x_j.view(-1, self.heads, self.out_channels)
        x_cat = torch.cat([x_i_view, x_j_view], dim=-1)
        alpha = F.leaky_relu((self.att * x_cat).sum(dim=-1)) 
        alpha = pyg_utils.softmax(alpha, edge_index_i, num_nodes=size_i)
```

**Comment by LFhase** [comment]
Hi, thanks for your attention.

As for the performance, you may check out the details about the hyperparameters [here](https://github.com/LFhase/Learning_CS224w/blob/master/Homework/HW2/report/hw2_submission_template.pdf). 

As for the error, please check if your other parts of code like data loading, training initialization work well by testing some simple model architectures work well. Otherwise, I may have no other ideas. You are encouraged to google the error to tackle it : (

BTW, you are encouraged to implement mini-batch training of GraphSage and GAT by checking out PyG examples and the original implementation of the authors and evaluate it over large-scale datasets like reddit and ogb-*. Thus, you may get more familiar with these models ; )
